- name: Create FTP data directory
  file:
    path: /mnt/storage/ftp/data
    state: directory
    owner: daniel
    group: daniel
    mode: '0755'

- name: Ensure user daniel is in ftp group
  ansible.builtin.user:
    name: daniel
    groups: games
    append: yes
  become: yes

- name: Pull FTP server Docker image
  community.docker.docker_image_pull:
    name: "fauria/vsftpd:latest@sha256:6d71d7c7f1b0ab2844ec7dc7999a30aef6d758b6d8179cf5967513f87c79c177"
    pull: not_present

- name: Start FTP container
  community.docker.docker_container:
    name: ftp_server
    image: "fauria/vsftpd:latest@sha256:6d71d7c7f1b0ab2844ec7dc7999a30aef6d758b6d8179cf5967513f87c79c177"
    ports:
      - "21:21"
    volumes:
      - "/mnt/storage/ftp/data:/home/vsftpd"
    env:
      FTP_USER: ftpuser
      FTP_PASS: "{{ ftp_password }}"
      PASV_ENABLE: "NO"
      WRITE_ENABLE: "YES"
      ANONYMOUS_ENABLE: "NO"
      FILE_OPEN_MODE: "0660"
      LOCAL_UMASK: "007"
    state: started
    restart_policy: always
