- name: Pull the Caddy Docker image
  community.docker.docker_image_pull:
    name: "caddy:2.11.4@sha256:844f60b64e4724a5aa8245e019dace0d3f199f7433ce6c57676cb30a920dbad9"
    pull: not_present

- name: Create Caddy Docker network
  community.docker.docker_network:
    name: caddy_network

- name: Create Caddy root directory
  file:
    path: /mnt/storage/config/caddy
    state: directory
    owner: daniel
    group: daniel
    mode: '0755'

- name: Create Caddy data directory
  file:
    path: /mnt/storage/config/caddy/data
    state: directory
    owner: daniel
    group: daniel
    mode: '0755'

- name: Create Caddy config directory
  file:
    path: /mnt/storage/config/caddy/config
    state: directory
    owner: daniel
    group: daniel
    mode: '0755'

- name: Put Caddy config in place
  copy:
    dest: /mnt/storage/config/caddy/Caddyfile
    content: |
      budget.home.danmidwood.com {
        reverse_proxy actual_budget:5006
      }

      plex.home.danmidwood.com {
        reverse_proxy plex:32400
      }

      grafana.home.danmidwood.com {
        reverse_proxy grafana:3000
      }

      photos.home.danmidwood.com {
        reverse_proxy immich-server:2283
      }

      books.home.danmidwood.com {
        reverse_proxy kavita:5000
      }

      projectboard.home.danmidwood.com {
        reverse_proxy planka:1337
      }

      passwords.home.danmidwood.com {
        reverse_proxy vaultwarden:80
      }

- name: Run Caddy container
  community.docker.docker_container:
    name: "caddy"
    image: "caddy:2.11.4@sha256:844f60b64e4724a5aa8245e019dace0d3f199f7433ce6c57676cb30a920dbad9"
    state: started
    restart_policy: always
    volumes:
      - /mnt/storage/config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /mnt/storage/config/caddy/data:/data
      - /mnt/storage/config/caddy/config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - name: caddy_network
