- name: Install Daniel's dependencies
  package:
    name:
      - git
      - openssh
      - sudo
      - zsh
    state: present

- name: Ensure user is present
  ansible.builtin.user:
    name: daniel
    groups: wheel
    shell: /bin/zsh
    state: present
    password: "{{ daniel_password | password_hash('sha512') }}"

- name: Ensure wheel group is in the sudoers list
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^# %wheel ALL=(ALL) ALL'
    line: '%wheel ALL=(ALL) ALL'
    state: present
    validate: 'visudo -cf %s'

- name: Add user to sudoers with no password requirement
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^daniel '
    line: 'daniel ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'

- name: Clone Oh My Zsh repository
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/daniel/.oh-my-zsh
    version: master
    force: yes
    update: yes
    accept_hostkey: yes
  become_user: daniel

- name: Copy the default .zshrc template for Oh My Zsh
  copy:
    src: /home/daniel/.oh-my-zsh/templates/zshrc.zsh-template
    dest: /home/daniel/.zshrc
    remote_src: yes
    owner: daniel
    group: daniel
    mode: '0644'

- name: Set Oh My Zsh theme to xiong-chiamiov-plus
  lineinfile:
    path: /home/daniel/.zshrc
    owner: daniel
    group: daniel
    mode: '0644'
    line: 'ZSH_THEME=xiong-chiamiov-plus'
    regexp: '^ZSH_THEME='

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/daniel/.ssh
    state: directory
    owner: daniel
    group: daniel
    mode: '0700'

- name: Add public key to authorized_keys
  ansible.builtin.copy:
    dest: /home/daniel/.ssh/authorized_keys
    content: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH3z/AM35YYthOkWQIXgJzqByoTI3u2W9H0J23ytEQBN daniel@obrizumgroup.com"
    owner: daniel
    group: daniel
    mode: '0600'
