- name: Pull the Planka Docker image
  community.docker.docker_image_pull:
    name: "ghcr.io/plankanban/planka:1.26.3@sha256:e469d724985db3f560ef0aa2218d54536212459bf8ecbdbc9fd995fc3cbe29db"
    pull: not_present

- name: Pull the 16-alpine Postgres Docker image
  community.docker.docker_image_pull:
    name: "postgres:16-alpine@sha256:d898b0b78a2627cb4ee63464a14efc9d296884f1b28c841b0ab7d7c42f1fffdf"
    pull: not_present

- name: Create Docker network
  community.docker.docker_network:
    name: planka_network

- name: Run Postgres container
  community.docker.docker_container:
    name: "planka-postgres"
    image: "postgres:16-alpine@sha256:d898b0b78a2627cb4ee63464a14efc9d296884f1b28c841b0ab7d7c42f1fffdf"
    state: started
    restart_policy: always
    volumes:
      - /mnt/storage/config/planka/db-data:/var/lib/postgresql/data
    env:
      POSTGRES_DB: "planka"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - name: planka_network

- name: Run Planka container
  community.docker.docker_container:
    name: "planka"
    image: "ghcr.io/plankanban/planka:1.26.3@sha256:e469d724985db3f560ef0aa2218d54536212459bf8ecbdbc9fd995fc3cbe29db"
    state: started
    restart_policy: always
    volumes:
      - /mnt/storage/config/planka/user-avatars:/app/public/user-avatars
      - /mnt/storage/config/planka/project-background-images:/app/public/project-background-images
      - /mnt/storage/config/planka/attachments:/app/private/attachments
    networks:
      - name: planka_network
      - name: caddy_network
    env_file: /mnt/storage/config/planka/.env
    env:
      BASE_URL: https://projectboard.home.danmidwood.com
      DATABASE_URL: postgresql://postgres@planka-postgres/planka
      DEFAULT_ADMIN_EMAIL: danieljamesmidwood@gmail.com
      DEFAULT_ADMIN_NAME: Daniel Midwood
      DEFAULT_ADMIN_USERNAME: daniel
