- name: Ensure logind.conf exists
  lineinfile:
    path: /etc/systemd/logind.conf
    state: present
    create: yes
    backup: yes
    line: 'HandleLidSwitchExternalPower=ignore'
  notify: Restart systemd-logind
