- name: Pull the Vaultwarden Docker image
  community.docker.docker_image_pull:
    name: "vaultwarden/server:1.37.1@sha256:ebdfe70701c60ac0c28c697e787cea767d7972940b786037b29fe0d507f821e8"
    pull: not_present

- name: Create Vaultwarden data directory
  file:
    path: /mnt/storage/config/vaultwarden
    state: directory
    owner: daniel
    group: daniel
    mode: '0755'

- name: Run Vaultwarden container
  community.docker.docker_container:
    name: "vaultwarden"
    image: "vaultwarden/server:1.37.1@sha256:ebdfe70701c60ac0c28c697e787cea767d7972940b786037b29fe0d507f821e8"
    state: started
    restart_policy: always
    volumes:
      - /mnt/storage/config/vaultwarden:/data
    env:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      ADMIN_TOKEN: "{{ vaultwarden_admin_token }}"
      DOMAIN: "https://passwords.home.danmidwood.com"
    networks:
      - name: caddy_network
