- name: Pull Portainer image
  community.docker.docker_image_pull:
    name: "portainer/portainer-ce:2.39.6@sha256:3fa8750ac2b98ce56784ca292df1adc3ec38f0062fd572811ea4b2221beee310"
    pull: not_present

- name: Create Portainer volume
  community.docker.docker_volume:
    name: portainer_data

- name: Run Portainer container
  community.docker.docker_container:
    name: portainer
    image: "portainer/portainer-ce:2.39.6@sha256:3fa8750ac2b98ce56784ca292df1adc3ec38f0062fd572811ea4b2221beee310"
    state: started
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
