- name: Ensure Python requests is installed
  ansible.builtin.package:
    name:
      - python-requests
    state: present

- name: Pull the Kavita Docker image
  community.docker.docker_image_pull:
    name: "linuxserver/kavita:v0.9.0.2-ls120@sha256:7e3be67100797e264756e9a1a9c6dd821c5dc0950b7940a645a629a429831118"
    pull: not_present

- name: Run Kavita container
  community.docker.docker_container:
    name: "kavita"
    image: "linuxserver/kavita:v0.9.0.2-ls120@sha256:7e3be67100797e264756e9a1a9c6dd821c5dc0950b7940a645a629a429831118"
    state: started
    restart_policy: always
    networks:
      - name: caddy_network
    volumes:
      - kavita_config:/config
      - /mnt/tmdas/Books:/books
    env:
      TZ: "Europe/London"
      PUID: "1000"
      GUID: "1000"
