- name: Install packages
  pacman:
    name:
      - emacs
      - less
    state: present

- name: Set timezone
  community.general.timezone:
    name: "Europe/London"

- name: Set locale
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: '^#en_GB.UTF-8 UTF-8'
    line: 'en_GB.UTF-8 UTF-8'
    state: present

- name: Comment out all other locales
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: '^(?!#en_GB.UTF-8 UTF-8)'
    line: '# \0'
    state: present

- name: Generate locale
  ansible.builtin.command: locale-gen
  changed_when: false

- name: Set LANG environment variable
  ansible.builtin.lineinfile:
    path: /etc/locale.conf
    line: 'LANG=en_GB.UTF-8'
    create: true

- name: Set hostname
  ansible.builtin.hostname:
    name: xps.home.danmidwood.com
    use: systemd
