- name: Pull the Actual Budget Docker image
  community.docker.docker_image_pull:
    name: "actualbudget/actual-server:26.8.1@sha256:6478d9ddfc0924479c09e6699c205e354c6f2216dfe7de3c0fb7b590d6edcdc5"
    pull: not_present

- name: Create Actual Budget data directory
  file:
    path: /mnt/storage/config/actual-budget/data
    state: directory
    owner: daniel
    group: daniel
    mode: '0755'


- name: Run Actual Budget container
  community.docker.docker_container:
    name: "actual_budget"
    image: "actualbudget/actual-server:26.8.1@sha256:6478d9ddfc0924479c09e6699c205e354c6f2216dfe7de3c0fb7b590d6edcdc5"
    state: started
    restart_policy: always
    volumes:
      - /mnt/storage/config/actual-budget/data:/data
    networks:
      - name: caddy_network
