- name: Ensure docker volume directory exists so we can mount it
  ansible.builtin.file:
    path: /var/lib/docker/volumes
    state: directory
    owner: root
    group: root
    mode: '0710'

- name: Add a mount to store the docker volumes on the DAS
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/mnt/tmdas/dockervolumes /var/lib/docker/volumes none bind 0 0"
    state: present
    backup: yes
  become: yes

- name: Mount the docker volumes directory
  ansible.builtin.mount:
    path: /var/lib/docker/volumes
    src: /mnt/tmdas/dockervolumes
    fstype: none
    opts: bind
    state: mounted
  become: yes

- name: Ensure Docker is installed
  package:
    name: docker
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: true
    state: started
    daemon_reload: true

- name: Add daniel user to Docker group
  user:
    name: daniel
    groups: docker
    append: true

