- name: Restart Prometheus
  community.docker.docker_container:
    name: prometheus
    state: started
    restart: true

- name: Restart node-exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    state: restarted

- name: Reload systemd for SMART collector
  ansible.builtin.systemd:
    daemon_reload: true
