- name: Configure XPS server
  hosts: xps
  become: true
  vars_files:
    - ../user_passwords.yml
  roles:
    - network
    - sshd
    - daniel
    - common
    - laptop_always_on
    - disks
    - makemkv
    - docker
    - plex
    - grafana
    - portainer
    - kavita
    - planka
