- name: Configure XPS server
  hosts: xps
  become: true
  roles:
    - network
    - sshd
    - daniel
    - common
    - laptop_always_on
    - disks
    - makemkv
    - docker
    - plex
    - grafana
    - portainer
